#!/usr/bin/env node
// Session 11 — run verify_brand.mjs over all brand JSONs and write per-brand raw output.
// Output: reports/verification_session11/<brand>_verify_raw.json
// And: reports/session11_verification_summary.md

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';

const ROOT = 'C:/Users/nadea/car-catalogs';
const DATA_DIR = `${ROOT}/data`;
const OUT_DIR = `${ROOT}/reports/verification_session11`;

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const brands = readdirSync(DATA_DIR)
  .filter(f => f.endsWith('.json') && !f.endsWith('.bak'))
  .map(f => f.replace('.json',''))
  .sort();

const rows = [];
let totalBlockers = 0, totalWarnings = 0, totalFyis = 0;

for (const slug of brands) {
  try {
    const out = execSync(`node "${ROOT}/scripts/verify_brand.mjs" ${slug}`, { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 });
    const parsed = JSON.parse(out);
    writeFileSync(`${OUT_DIR}/${slug}_verify_raw.json`, JSON.stringify(parsed, null, 2));
    rows.push({
      brand: parsed.brand || slug,
      slug,
      models: parsed.model_count,
      trims: parsed.trim_count,
      images: parsed.total_images,
      blockers: parsed.blocker_count,
      warnings: parsed.warning_count,
      fyis: parsed.fyi_count
    });
    totalBlockers += parsed.blocker_count || 0;
    totalWarnings += parsed.warning_count || 0;
    totalFyis += parsed.fyi_count || 0;
  } catch (err) {
    console.error(`FAIL ${slug}: ${err.message.split('\n')[0]}`);
    rows.push({ brand: slug, slug, error: err.message.split('\n')[0] });
  }
}

// Markdown summary
let md = '# Session 11 verification summary\n\nGenerated by `scripts/verify_session11_batch.mjs` using the patched verifier.\n\n';
md += '## Per-brand summary\n\n| brand | models | trims | images | blockers | warnings | fyis |\n|---|---:|---:|---:|---:|---:|---:|\n';
for (const r of rows) {
  if (r.error) {
    md += `| ${r.brand} | — | — | — | ERROR | — | — |\n`;
  } else {
    md += `| ${r.brand} | ${r.models} | ${r.trims} | ${r.images} | ${r.blockers} | ${r.warnings} | ${r.fyis} |\n`;
  }
}
md += `\n## Totals\n\n- Brands verified: ${rows.filter(r=>!r.error).length}\n- Total blockers: **${totalBlockers}**\n- Total warnings: ${totalWarnings}\n- Total FYIs: ${totalFyis}\n\n`;
md += '## Brands with blockers\n\n';
const withBlockers = rows.filter(r => !r.error && r.blockers > 0);
if (withBlockers.length === 0) {
  md += '_None — all brands verified clean._\n';
} else {
  for (const r of withBlockers) {
    md += `- **${r.slug}** — ${r.blockers} blocker(s); see \`reports/verification_session11/${r.slug}_verify_raw.json\`\n`;
  }
}

writeFileSync(`${ROOT}/reports/session11_verification_summary.md`, md);
console.log(`\nWrote ${rows.length} per-brand reports to ${OUT_DIR}/`);
console.log(`Summary: ${ROOT}/reports/session11_verification_summary.md`);
console.log(`Totals: blockers=${totalBlockers} warnings=${totalWarnings} fyis=${totalFyis}`);
