#!/usr/bin/env node
// Run verify_brand.mjs across all brands modified in Session 10 and write
// per-brand raw JSON output to reports/verification_session10/<brand>_verify_raw.json.
// Also produce a consolidated reports/session10_verification_summary.md.
//
// Brands targeted: all 5 new brands (chrysler, dodge, fiat, bugatti, vinfast) +
// 3 Phase A modified brands (mercedes-benz, gmc, rolls-royce) +
// Phase C modified brands.

import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const PROJECT_ROOT = path.resolve(path.dirname(__filename), "..");

const BRANDS = [
  // New brands (B2)
  "chrysler", "dodge", "fiat", "bugatti", "vinfast",
  // Phase A modified
  "mercedes-benz", "gmc", "rolls-royce",
  // Phase C modified — German luxury
  "bmw", "audi",
  // Phase C — Japanese
  "honda", "toyota", "lexus", "acura", "mazda", "mitsubishi",
  // Phase C — Asian/Korean
  "hyundai", "kia", "nissan", "infiniti", "subaru", "mini",
  // Phase C — American big-three
  "ford", "chevrolet", "cadillac", "buick",
  // Phase C — Stellantis + Euro mainstream
  "jeep", "ram", "volkswagen", "volvo", "alfa-romeo", "maserati", "jaguar", "land-rover",
  // Phase C — EV-only
  "tesla", "polestar", "rivian", "lucid",
];

const OUT_DIR = path.join(PROJECT_ROOT, "reports", "verification_session10");
mkdirSync(OUT_DIR, { recursive: true });

const summary = [];

for (const brand of BRANDS) {
  const dataPath = path.join(PROJECT_ROOT, "data", `${brand}.json`);
  try {
    readFileSync(dataPath, "utf8");
  } catch {
    console.log(`SKIP (no data file): ${brand}`);
    continue;
  }
  let raw;
  try {
    raw = execFileSync("node", [path.join(PROJECT_ROOT, "scripts", "verify_brand.mjs"), brand], { encoding: "utf-8" });
  } catch (e) {
    summary.push({ brand, blockers: -1, warnings: -1, fyis: -1, error: e.message });
    continue;
  }
  let j;
  try {
    j = JSON.parse(raw);
  } catch (e) {
    summary.push({ brand, blockers: -1, warnings: -1, fyis: -1, error: "could not parse verifier JSON: " + e.message });
    continue;
  }
  writeFileSync(path.join(OUT_DIR, `${brand}_verify_raw.json`), JSON.stringify(j, null, 2));
  summary.push({
    brand,
    models: j.model_count,
    trims: j.trim_count,
    images: j.total_images,
    needs_scraping: j.needs_scraping || 0,
    blockers: j.blocker_count,
    warnings: j.warning_count,
    fyis: j.fyi_count,
  });
  process.stdout.write(`  ${brand.padEnd(16)} models:${(j.model_count || 0).toString().padStart(2)} trims:${(j.trim_count || 0).toString().padStart(3)} blockers:${(j.blocker_count || 0).toString().padStart(2)} warnings:${(j.warning_count || 0).toString().padStart(3)} fyis:${(j.fyi_count || 0).toString().padStart(2)}\n`);
}

// Consolidated MD summary
let md = `# Session 10 verification summary\n\nGenerated by \`scripts/verify_session10_batch.mjs\`. Per-brand raw JSON at \`reports/verification_session10/<brand>_verify_raw.json\`.\n\n## Per-brand summary\n\n| brand | models | trims | images | blockers | warnings | fyis |\n|---|---:|---:|---:|---:|---:|---:|\n`;
let totalBlockers = 0, totalWarnings = 0, totalFyis = 0;
for (const s of summary) {
  if (s.error) {
    md += `| ${s.brand} | — | — | — | ERROR | — | — |\n`;
    continue;
  }
  totalBlockers += s.blockers;
  totalWarnings += s.warnings;
  totalFyis += s.fyis;
  md += `| ${s.brand} | ${s.models || 0} | ${s.trims || 0} | ${s.images || 0} | ${s.blockers} | ${s.warnings} | ${s.fyis} |\n`;
}
md += `\n## Totals\n\n- Brands verified: ${summary.length}\n- Total blockers: **${totalBlockers}**\n- Total warnings: ${totalWarnings}\n- Total FYIs: ${totalFyis}\n\n`;

if (totalBlockers > 0) {
  md += `## Brands with blockers\n\n`;
  for (const s of summary) {
    if (s.blockers > 0) md += `- **${s.brand}** — ${s.blockers} blocker(s); see \`reports/verification_session10/${s.brand}_verify_raw.json\`\n`;
  }
}

writeFileSync(path.join(PROJECT_ROOT, "reports", "session10_verification_summary.md"), md);
console.log(`\nWrote consolidated summary: reports/session10_verification_summary.md`);
console.log(`Total blockers across ${summary.length} brands: ${totalBlockers}`);
